version: "3.9"

services:

  api:
    image: deadlights7865/crypto-api:latest
    container_name: crypto-api
    ports:
      - "8010:8010"
    restart: always

  collector:
    image: deadlights7865/crypto-collector:latest
    container_name: crypto-collector
    restart: always

  aggregation:
    image: deadlights7865/crypto-aggregation:latest
    container_name: crypto-aggregation
    restart: always

  feature:
    image: deadlights7865/crypto-feature:latest
    container_name: crypto-feature
    restart: always

  frontend:
    image: deadlights7865/crypto-frontend:latest
    container_name: crypto-frontend
    ports:
      - "8003:80"
    restart: always