import os

AGGREGATION_SERVICE = os.getenv('AGGREGATION_SERVICE')
FEATURE_SERVICE = os.getenv('FEATURE_SERVICE')
COLLECTOR_SERVICE = os.getenv('COLLECTOR_SERVICE')
API_SERVICE = os.getenv("API_SERVICE")
