from sqlalchemy import Column, Integer, Numeric, String, DateTime, ForeignKey
from sqlalchemy.sql import func

from aggregation_src.models.base import Base

class CryptoCandle1m(Base):
    """
    ORM models mapping to crypto_candles_1m table.

    This table stores aggregate market data from "crypto_prices".
    Each row represents a single-minute candle for a specific asset.

    The data is generated by candle_scheduler.
    """

    __tablename__ = 'crypto_candles_1m'

    id = Column(Integer, primary_key=True)  # pk

    asset_id = Column(Integer, nullable=False)  # reference to table crypto_assets.assets_id

    candle_time = Column(DateTime, nullable=False)  # 10:15:00 candle represents the candle 10:15:00 - 10:15:59

    open = Column(Numeric(18, 8))

    high = Column(Numeric(18, 8))

    low = Column(Numeric(18, 8))

    close = Column(Numeric(18, 8))

    created_at = Column(DateTime, server_default=func.now())